// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/module.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModuleCreateRequest struct {
	Name                      string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Subsribestoevent          string            `protobuf:"bytes,2,opt,name=subsribestoevent" json:"subsribestoevent,omitempty"`
	Eventspublished           string            `protobuf:"bytes,3,opt,name=eventspublished" json:"eventspublished,omitempty"`
	Moduleimage               string            `protobuf:"bytes,4,opt,name=moduleimage" json:"moduleimage,omitempty"`
	Moduleimagetag            string            `protobuf:"bytes,5,opt,name=moduleimagetag" json:"moduleimagetag,omitempty"`
	Handlerimage              string            `protobuf:"bytes,6,opt,name=handlerimage" json:"handlerimage,omitempty"`
	Handlerimagetag           string            `protobuf:"bytes,7,opt,name=handlerimagetag" json:"handlerimagetag,omitempty"`
	InstanceCount             int32             `protobuf:"varint,8,opt,name=instanceCount" json:"instanceCount,omitempty"`
	Retrycount                int32             `protobuf:"varint,9,opt,name=retrycount" json:"retrycount,omitempty"`
	Containerregistryurl      string            `protobuf:"bytes,10,opt,name=containerregistryurl" json:"containerregistryurl,omitempty"`
	Containerregistryusername string            `protobuf:"bytes,11,opt,name=containerregistryusername" json:"containerregistryusername,omitempty"`
	Containerregistrypassword string            `protobuf:"bytes,12,opt,name=containerregistrypassword" json:"containerregistrypassword,omitempty"`
	Containerregistryemail    string            `protobuf:"bytes,13,opt,name=containerregistryemail" json:"containerregistryemail,omitempty"`
	Configmap                 map[string]string `protobuf:"bytes,14,rep,name=configmap" json:"configmap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral      struct{}          `json:"-"`
	XXX_unrecognized          []byte            `json:"-"`
	XXX_sizecache             int32             `json:"-"`
}

func (m *ModuleCreateRequest) Reset()         { *m = ModuleCreateRequest{} }
func (m *ModuleCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ModuleCreateRequest) ProtoMessage()    {}
func (*ModuleCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_4b93e9cbb82d0360, []int{0}
}
func (m *ModuleCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleCreateRequest.Unmarshal(m, b)
}
func (m *ModuleCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleCreateRequest.Marshal(b, m, deterministic)
}
func (dst *ModuleCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleCreateRequest.Merge(dst, src)
}
func (m *ModuleCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ModuleCreateRequest.Size(m)
}
func (m *ModuleCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleCreateRequest proto.InternalMessageInfo

func (m *ModuleCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleCreateRequest) GetSubsribestoevent() string {
	if m != nil {
		return m.Subsribestoevent
	}
	return ""
}

func (m *ModuleCreateRequest) GetEventspublished() string {
	if m != nil {
		return m.Eventspublished
	}
	return ""
}

func (m *ModuleCreateRequest) GetModuleimage() string {
	if m != nil {
		return m.Moduleimage
	}
	return ""
}

func (m *ModuleCreateRequest) GetModuleimagetag() string {
	if m != nil {
		return m.Moduleimagetag
	}
	return ""
}

func (m *ModuleCreateRequest) GetHandlerimage() string {
	if m != nil {
		return m.Handlerimage
	}
	return ""
}

func (m *ModuleCreateRequest) GetHandlerimagetag() string {
	if m != nil {
		return m.Handlerimagetag
	}
	return ""
}

func (m *ModuleCreateRequest) GetInstanceCount() int32 {
	if m != nil {
		return m.InstanceCount
	}
	return 0
}

func (m *ModuleCreateRequest) GetRetrycount() int32 {
	if m != nil {
		return m.Retrycount
	}
	return 0
}

func (m *ModuleCreateRequest) GetContainerregistryurl() string {
	if m != nil {
		return m.Containerregistryurl
	}
	return ""
}

func (m *ModuleCreateRequest) GetContainerregistryusername() string {
	if m != nil {
		return m.Containerregistryusername
	}
	return ""
}

func (m *ModuleCreateRequest) GetContainerregistrypassword() string {
	if m != nil {
		return m.Containerregistrypassword
	}
	return ""
}

func (m *ModuleCreateRequest) GetContainerregistryemail() string {
	if m != nil {
		return m.Containerregistryemail
	}
	return ""
}

func (m *ModuleCreateRequest) GetConfigmap() map[string]string {
	if m != nil {
		return m.Configmap
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_4b93e9cbb82d0360, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ModuleCreateRequest)(nil), "ModuleCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "ModuleCreateRequest.ConfigmapEntry")
	proto.RegisterType((*Empty)(nil), "Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleServiceClient interface {
	Create(ctx context.Context, in *ModuleCreateRequest, opts ...grpc.CallOption) (*Empty, error)
}

type moduleServiceClient struct {
	cc *grpc.ClientConn
}

func NewModuleServiceClient(cc *grpc.ClientConn) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) Create(ctx context.Context, in *ModuleCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ModuleService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServiceServer is the server API for ModuleService service.
type ModuleServiceServer interface {
	Create(context.Context, *ModuleCreateRequest) (*Empty, error)
}

func RegisterModuleServiceServer(s *grpc.Server, srv ModuleServiceServer) {
	s.RegisterService(&_ModuleService_serviceDesc, srv)
}

func _ModuleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ModuleService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Create(ctx, req.(*ModuleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ModuleService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/module.proto",
}

func init() { proto.RegisterFile("protobuf/module.proto", fileDescriptor_module_4b93e9cbb82d0360) }

var fileDescriptor_module_4b93e9cbb82d0360 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x49, 0x53, 0xa7, 0xcd, 0xa4, 0x09, 0xd5, 0x10, 0xd0, 0xd2, 0x03, 0x8a, 0x02, 0x42,
	0x11, 0x87, 0x20, 0x05, 0x09, 0x01, 0xea, 0x05, 0xa2, 0x1e, 0xb9, 0x84, 0x1b, 0xb7, 0xb5, 0x3d,
	0x75, 0x57, 0xd8, 0xbb, 0x66, 0xff, 0x04, 0xf9, 0x0b, 0xf2, 0xb9, 0x90, 0xc7, 0x8d, 0x70, 0x12,
	0xe7, 0x36, 0xf3, 0x9b, 0xf7, 0x76, 0x9f, 0xb4, 0xb3, 0xf0, 0xbc, 0xb4, 0xc6, 0x9b, 0x38, 0xdc,
	0xbf, 0x2f, 0x4c, 0x1a, 0x72, 0x5a, 0x72, 0x3f, 0xff, 0x1b, 0xc1, 0xb3, 0xef, 0x0c, 0xd6, 0x96,
	0xa4, 0xa7, 0x0d, 0xfd, 0x0e, 0xe4, 0x3c, 0x22, 0x9c, 0x6b, 0x59, 0x90, 0xe8, 0xcd, 0x7a, 0x8b,
	0xe1, 0x86, 0x6b, 0x7c, 0x07, 0xd7, 0x2e, 0xc4, 0xce, 0xaa, 0x98, 0x9c, 0x37, 0xb4, 0x25, 0xed,
	0xc5, 0x19, 0xcf, 0x8f, 0x38, 0x2e, 0xe0, 0x29, 0x17, 0xae, 0x0c, 0x71, 0xae, 0xdc, 0x03, 0xa5,
	0xa2, 0xcf, 0xd2, 0x43, 0x8c, 0x33, 0x18, 0x35, 0x89, 0x54, 0x21, 0x33, 0x12, 0xe7, 0xac, 0x6a,
	0x23, 0x7c, 0x0b, 0x93, 0x56, 0xeb, 0x65, 0x26, 0x22, 0x16, 0x1d, 0x50, 0x9c, 0xc3, 0xd5, 0x83,
	0xd4, 0x69, 0x4e, 0xb6, 0x39, 0x6a, 0xc0, 0xaa, 0x3d, 0x56, 0xe7, 0x6a, 0xf7, 0xf5, 0x61, 0x17,
	0x4d, 0xae, 0x03, 0x8c, 0x6f, 0x60, 0xac, 0xb4, 0xf3, 0x52, 0x27, 0xb4, 0x36, 0x41, 0x7b, 0x71,
	0x39, 0xeb, 0x2d, 0xa2, 0xcd, 0x3e, 0xc4, 0x57, 0x00, 0x96, 0xbc, 0xad, 0x12, 0x96, 0x0c, 0x59,
	0xd2, 0x22, 0xb8, 0x82, 0x69, 0x62, 0xb4, 0x97, 0x4a, 0x93, 0xb5, 0x94, 0x29, 0xe7, 0x6d, 0x15,
	0x6c, 0x2e, 0x80, 0x2f, 0xed, 0x9c, 0xe1, 0x2d, 0xbc, 0x3c, 0xe6, 0x8e, 0x2c, 0x3f, 0xc8, 0x88,
	0x8d, 0xa7, 0x05, 0x9d, 0xee, 0x52, 0x3a, 0xf7, 0xc7, 0xd8, 0x54, 0x5c, 0x9d, 0x70, 0xef, 0x04,
	0xf8, 0x11, 0x5e, 0x1c, 0x0d, 0xa9, 0x90, 0x2a, 0x17, 0x63, 0xb6, 0x9e, 0x98, 0xe2, 0x57, 0x18,
	0x26, 0x46, 0xdf, 0xab, 0xac, 0x90, 0xa5, 0x98, 0xcc, 0xfa, 0x8b, 0xd1, 0xea, 0xf5, 0xb2, 0x63,
	0xb1, 0x96, 0xeb, 0x9d, 0xea, 0x4e, 0x7b, 0x5b, 0x6d, 0xfe, 0xbb, 0x6e, 0x6e, 0x61, 0xb2, 0x3f,
	0xc4, 0x6b, 0xe8, 0xff, 0xa2, 0xea, 0x71, 0x07, 0xeb, 0x12, 0xa7, 0x10, 0x6d, 0x65, 0x1e, 0xe8,
	0x71, 0xef, 0x9a, 0xe6, 0xcb, 0xd9, 0xa7, 0xde, 0xfc, 0x02, 0xa2, 0xbb, 0xa2, 0xf4, 0xd5, 0xea,
	0x33, 0x8c, 0x9b, 0x7b, 0x7f, 0x90, 0xdd, 0xaa, 0xa4, 0x7e, 0xf2, 0x41, 0x13, 0x01, 0xa7, 0x5d,
	0x89, 0x6e, 0x06, 0x4b, 0x36, 0xce, 0x9f, 0x7c, 0x83, 0x9f, 0x97, 0xbb, 0x5f, 0x12, 0x0f, 0xb8,
	0xfa, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x39, 0xf0, 0x41, 0x63, 0x38, 0x03, 0x00, 0x00,
}
