// Code generated by protoc-gen-go. DO NOT EDIT.
// source: module.proto

package module

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModuleCreateRequest struct {
	Modulename           string            `protobuf:"bytes,1,opt,name=modulename,proto3" json:"modulename,omitempty"`
	Eventsubscriptions   string            `protobuf:"bytes,2,opt,name=eventsubscriptions,proto3" json:"eventsubscriptions,omitempty"`
	Eventpublications    string            `protobuf:"bytes,3,opt,name=eventpublications,proto3" json:"eventpublications,omitempty"`
	Moduleimage          string            `protobuf:"bytes,4,opt,name=moduleimage,proto3" json:"moduleimage,omitempty"`
	Moduleimagetag       string            `protobuf:"bytes,5,opt,name=moduleimagetag,proto3" json:"moduleimagetag,omitempty"`
	Handlerimage         string            `protobuf:"bytes,6,opt,name=handlerimage,proto3" json:"handlerimage,omitempty"`
	Handlerimagetag      string            `protobuf:"bytes,7,opt,name=handlerimagetag,proto3" json:"handlerimagetag,omitempty"`
	Instancecount        int32             `protobuf:"varint,8,opt,name=instancecount,proto3" json:"instancecount,omitempty"`
	Retrycount           int32             `protobuf:"varint,9,opt,name=retrycount,proto3" json:"retrycount,omitempty"`
	Provider             string            `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`
	Configmap            map[string]string `protobuf:"bytes,11,rep,name=configmap,proto3" json:"configmap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModuleCreateRequest) Reset()         { *m = ModuleCreateRequest{} }
func (m *ModuleCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ModuleCreateRequest) ProtoMessage()    {}
func (*ModuleCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{0}
}
func (m *ModuleCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleCreateRequest.Unmarshal(m, b)
}
func (m *ModuleCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleCreateRequest.Marshal(b, m, deterministic)
}
func (dst *ModuleCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleCreateRequest.Merge(dst, src)
}
func (m *ModuleCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ModuleCreateRequest.Size(m)
}
func (m *ModuleCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleCreateRequest proto.InternalMessageInfo

func (m *ModuleCreateRequest) GetModulename() string {
	if m != nil {
		return m.Modulename
	}
	return ""
}

func (m *ModuleCreateRequest) GetEventsubscriptions() string {
	if m != nil {
		return m.Eventsubscriptions
	}
	return ""
}

func (m *ModuleCreateRequest) GetEventpublications() string {
	if m != nil {
		return m.Eventpublications
	}
	return ""
}

func (m *ModuleCreateRequest) GetModuleimage() string {
	if m != nil {
		return m.Moduleimage
	}
	return ""
}

func (m *ModuleCreateRequest) GetModuleimagetag() string {
	if m != nil {
		return m.Moduleimagetag
	}
	return ""
}

func (m *ModuleCreateRequest) GetHandlerimage() string {
	if m != nil {
		return m.Handlerimage
	}
	return ""
}

func (m *ModuleCreateRequest) GetHandlerimagetag() string {
	if m != nil {
		return m.Handlerimagetag
	}
	return ""
}

func (m *ModuleCreateRequest) GetInstancecount() int32 {
	if m != nil {
		return m.Instancecount
	}
	return 0
}

func (m *ModuleCreateRequest) GetRetrycount() int32 {
	if m != nil {
		return m.Retrycount
	}
	return 0
}

func (m *ModuleCreateRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *ModuleCreateRequest) GetConfigmap() map[string]string {
	if m != nil {
		return m.Configmap
	}
	return nil
}

type ModuleCreateResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleCreateResponse) Reset()         { *m = ModuleCreateResponse{} }
func (m *ModuleCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ModuleCreateResponse) ProtoMessage()    {}
func (*ModuleCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{1}
}
func (m *ModuleCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleCreateResponse.Unmarshal(m, b)
}
func (m *ModuleCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleCreateResponse.Marshal(b, m, deterministic)
}
func (dst *ModuleCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleCreateResponse.Merge(dst, src)
}
func (m *ModuleCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ModuleCreateResponse.Size(m)
}
func (m *ModuleCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleCreateResponse proto.InternalMessageInfo

func (m *ModuleCreateResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ModuleDeleteRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleDeleteRequest) Reset()         { *m = ModuleDeleteRequest{} }
func (m *ModuleDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ModuleDeleteRequest) ProtoMessage()    {}
func (*ModuleDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{2}
}
func (m *ModuleDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleDeleteRequest.Unmarshal(m, b)
}
func (m *ModuleDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *ModuleDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleDeleteRequest.Merge(dst, src)
}
func (m *ModuleDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ModuleDeleteRequest.Size(m)
}
func (m *ModuleDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleDeleteRequest proto.InternalMessageInfo

func (m *ModuleDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ModuleDeleteResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleDeleteResponse) Reset()         { *m = ModuleDeleteResponse{} }
func (m *ModuleDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ModuleDeleteResponse) ProtoMessage()    {}
func (*ModuleDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{3}
}
func (m *ModuleDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleDeleteResponse.Unmarshal(m, b)
}
func (m *ModuleDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *ModuleDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleDeleteResponse.Merge(dst, src)
}
func (m *ModuleDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ModuleDeleteResponse.Size(m)
}
func (m *ModuleDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleDeleteResponse proto.InternalMessageInfo

func (m *ModuleDeleteResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ModuleGetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleGetRequest) Reset()         { *m = ModuleGetRequest{} }
func (m *ModuleGetRequest) String() string { return proto.CompactTextString(m) }
func (*ModuleGetRequest) ProtoMessage()    {}
func (*ModuleGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{4}
}
func (m *ModuleGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleGetRequest.Unmarshal(m, b)
}
func (m *ModuleGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleGetRequest.Marshal(b, m, deterministic)
}
func (dst *ModuleGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleGetRequest.Merge(dst, src)
}
func (m *ModuleGetRequest) XXX_Size() int {
	return xxx_messageInfo_ModuleGetRequest.Size(m)
}
func (m *ModuleGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleGetRequest proto.InternalMessageInfo

func (m *ModuleGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// TODO: add more fields
type ModuleGetResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StatusMessage        string   `protobuf:"bytes,3,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleGetResponse) Reset()         { *m = ModuleGetResponse{} }
func (m *ModuleGetResponse) String() string { return proto.CompactTextString(m) }
func (*ModuleGetResponse) ProtoMessage()    {}
func (*ModuleGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{5}
}
func (m *ModuleGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleGetResponse.Unmarshal(m, b)
}
func (m *ModuleGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleGetResponse.Marshal(b, m, deterministic)
}
func (dst *ModuleGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleGetResponse.Merge(dst, src)
}
func (m *ModuleGetResponse) XXX_Size() int {
	return xxx_messageInfo_ModuleGetResponse.Size(m)
}
func (m *ModuleGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleGetResponse proto.InternalMessageInfo

func (m *ModuleGetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleGetResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ModuleGetResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type ModuleListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleListRequest) Reset()         { *m = ModuleListRequest{} }
func (m *ModuleListRequest) String() string { return proto.CompactTextString(m) }
func (*ModuleListRequest) ProtoMessage()    {}
func (*ModuleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{6}
}
func (m *ModuleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleListRequest.Unmarshal(m, b)
}
func (m *ModuleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleListRequest.Marshal(b, m, deterministic)
}
func (dst *ModuleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleListRequest.Merge(dst, src)
}
func (m *ModuleListRequest) XXX_Size() int {
	return xxx_messageInfo_ModuleListRequest.Size(m)
}
func (m *ModuleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleListRequest proto.InternalMessageInfo

type ModuleListResponse struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleListResponse) Reset()         { *m = ModuleListResponse{} }
func (m *ModuleListResponse) String() string { return proto.CompactTextString(m) }
func (*ModuleListResponse) ProtoMessage()    {}
func (*ModuleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{7}
}
func (m *ModuleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleListResponse.Unmarshal(m, b)
}
func (m *ModuleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleListResponse.Marshal(b, m, deterministic)
}
func (dst *ModuleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleListResponse.Merge(dst, src)
}
func (m *ModuleListResponse) XXX_Size() int {
	return xxx_messageInfo_ModuleListResponse.Size(m)
}
func (m *ModuleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleListResponse proto.InternalMessageInfo

func (m *ModuleListResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_module_1949e0d3d4d3b9f3, []int{8}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ModuleCreateRequest)(nil), "ModuleCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "ModuleCreateRequest.ConfigmapEntry")
	proto.RegisterType((*ModuleCreateResponse)(nil), "ModuleCreateResponse")
	proto.RegisterType((*ModuleDeleteRequest)(nil), "ModuleDeleteRequest")
	proto.RegisterType((*ModuleDeleteResponse)(nil), "ModuleDeleteResponse")
	proto.RegisterType((*ModuleGetRequest)(nil), "ModuleGetRequest")
	proto.RegisterType((*ModuleGetResponse)(nil), "ModuleGetResponse")
	proto.RegisterType((*ModuleListRequest)(nil), "ModuleListRequest")
	proto.RegisterType((*ModuleListResponse)(nil), "ModuleListResponse")
	proto.RegisterType((*Empty)(nil), "Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleServiceClient interface {
	Create(ctx context.Context, in *ModuleCreateRequest, opts ...grpc.CallOption) (*ModuleCreateResponse, error)
	Delete(ctx context.Context, in *ModuleDeleteRequest, opts ...grpc.CallOption) (*ModuleDeleteResponse, error)
	Get(ctx context.Context, in *ModuleGetRequest, opts ...grpc.CallOption) (*ModuleGetResponse, error)
	List(ctx context.Context, in *ModuleListRequest, opts ...grpc.CallOption) (*ModuleListResponse, error)
}

type moduleServiceClient struct {
	cc *grpc.ClientConn
}

func NewModuleServiceClient(cc *grpc.ClientConn) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) Create(ctx context.Context, in *ModuleCreateRequest, opts ...grpc.CallOption) (*ModuleCreateResponse, error) {
	out := new(ModuleCreateResponse)
	err := c.cc.Invoke(ctx, "/ModuleService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Delete(ctx context.Context, in *ModuleDeleteRequest, opts ...grpc.CallOption) (*ModuleDeleteResponse, error) {
	out := new(ModuleDeleteResponse)
	err := c.cc.Invoke(ctx, "/ModuleService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Get(ctx context.Context, in *ModuleGetRequest, opts ...grpc.CallOption) (*ModuleGetResponse, error) {
	out := new(ModuleGetResponse)
	err := c.cc.Invoke(ctx, "/ModuleService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) List(ctx context.Context, in *ModuleListRequest, opts ...grpc.CallOption) (*ModuleListResponse, error) {
	out := new(ModuleListResponse)
	err := c.cc.Invoke(ctx, "/ModuleService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServiceServer is the server API for ModuleService service.
type ModuleServiceServer interface {
	Create(context.Context, *ModuleCreateRequest) (*ModuleCreateResponse, error)
	Delete(context.Context, *ModuleDeleteRequest) (*ModuleDeleteResponse, error)
	Get(context.Context, *ModuleGetRequest) (*ModuleGetResponse, error)
	List(context.Context, *ModuleListRequest) (*ModuleListResponse, error)
}

func RegisterModuleServiceServer(s *grpc.Server, srv ModuleServiceServer) {
	s.RegisterService(&_ModuleService_serviceDesc, srv)
}

func _ModuleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ModuleService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Create(ctx, req.(*ModuleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ModuleService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Delete(ctx, req.(*ModuleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ModuleService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Get(ctx, req.(*ModuleGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ModuleService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).List(ctx, req.(*ModuleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ModuleService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ModuleService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ModuleService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ModuleService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "module.proto",
}

func init() { proto.RegisterFile("module.proto", fileDescriptor_module_1949e0d3d4d3b9f3) }

var fileDescriptor_module_1949e0d3d4d3b9f3 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe3, 0x26, 0x76, 0x9b, 0x49, 0x5b, 0x9a, 0x49, 0x40, 0x96, 0x0f, 0xc8, 0x5a, 0x50,
	0x15, 0x2a, 0x64, 0x89, 0x72, 0x00, 0x21, 0x2e, 0x50, 0xaa, 0x5e, 0xe8, 0x25, 0xdc, 0xb8, 0x6d,
	0x9c, 0x21, 0x58, 0xd8, 0x6b, 0xb3, 0xbb, 0x8e, 0x94, 0x97, 0xe0, 0x29, 0x79, 0x10, 0xe4, 0xdd,
	0x38, 0xb5, 0x13, 0xd3, 0xdb, 0xce, 0x3f, 0xdf, 0xcc, 0x24, 0xff, 0x4c, 0x02, 0xa7, 0x59, 0xbe,
	0x2c, 0x53, 0x8a, 0x0a, 0x99, 0xeb, 0x9c, 0xfd, 0x19, 0xc0, 0xe4, 0xde, 0x08, 0x37, 0x92, 0xb8,
	0xa6, 0x39, 0xfd, 0x2e, 0x49, 0x69, 0x7c, 0x0e, 0x60, 0x39, 0xc1, 0x33, 0xf2, 0x9d, 0xd0, 0x99,
	0x0d, 0xe7, 0x0d, 0x05, 0x23, 0x40, 0x5a, 0x93, 0xd0, 0xaa, 0x5c, 0xa8, 0x58, 0x26, 0x85, 0x4e,
	0x72, 0xa1, 0xfc, 0x23, 0xc3, 0x75, 0x64, 0xf0, 0x35, 0x8c, 0x8d, 0x5a, 0x94, 0x8b, 0x34, 0x89,
	0xb9, 0xc5, 0xfb, 0x06, 0x3f, 0x4c, 0x60, 0x08, 0x23, 0x3b, 0x2b, 0xc9, 0xf8, 0x8a, 0xfc, 0x81,
	0xe1, 0x9a, 0x12, 0x5e, 0xc2, 0x79, 0x23, 0xd4, 0x7c, 0xe5, 0xbb, 0x06, 0xda, 0x53, 0x91, 0xc1,
	0xe9, 0x4f, 0x2e, 0x96, 0x29, 0x49, 0xdb, 0xca, 0x33, 0x54, 0x4b, 0xc3, 0x19, 0x3c, 0x69, 0xc6,
	0x55, 0xb3, 0x63, 0x83, 0xed, 0xcb, 0xf8, 0x12, 0xce, 0x12, 0xa1, 0x34, 0x17, 0x31, 0xc5, 0x79,
	0x29, 0xb4, 0x7f, 0x12, 0x3a, 0x33, 0x77, 0xde, 0x16, 0x2b, 0xef, 0x24, 0x69, 0xb9, 0xb1, 0xc8,
	0xd0, 0x20, 0x0d, 0x05, 0x03, 0x38, 0x29, 0x64, 0xbe, 0x4e, 0x96, 0x24, 0x7d, 0x30, 0x83, 0x76,
	0x31, 0x7e, 0x82, 0x61, 0x9c, 0x8b, 0x1f, 0xc9, 0x2a, 0xe3, 0x85, 0x3f, 0x0a, 0xfb, 0xb3, 0xd1,
	0xf5, 0x8b, 0xa8, 0x63, 0x41, 0xd1, 0x4d, 0x4d, 0xdd, 0x0a, 0x2d, 0x37, 0xf3, 0x87, 0xaa, 0xe0,
	0x23, 0x9c, 0xb7, 0x93, 0x78, 0x01, 0xfd, 0x5f, 0xb4, 0xd9, 0x6e, 0xb1, 0x7a, 0xe2, 0x14, 0xdc,
	0x35, 0x4f, 0x4b, 0xda, 0x6e, 0xcc, 0x06, 0x1f, 0x8e, 0xde, 0x3b, 0xec, 0x0a, 0xa6, 0xed, 0x71,
	0xaa, 0xc8, 0x85, 0x22, 0x44, 0x18, 0x34, 0x4e, 0xc1, 0xbc, 0xd9, 0xab, 0xfa, 0x76, 0xbe, 0x50,
	0x4a, 0x0f, 0xb7, 0xd3, 0x85, 0xee, 0xda, 0xd6, 0xe8, 0x23, 0x6d, 0x2f, 0xe1, 0xc2, 0xb2, 0x77,
	0xa4, 0x1f, 0xeb, 0x49, 0x30, 0x6e, 0x70, 0xff, 0x6f, 0x88, 0xcf, 0xc0, 0x53, 0x9a, 0xeb, 0xb2,
	0x3e, 0xd0, 0x6d, 0x54, 0xad, 0xd3, 0xbe, 0xee, 0x49, 0xa9, 0xea, 0x3a, 0xec, 0x41, 0xb6, 0x45,
	0x36, 0xa9, 0xc7, 0x7c, 0x4d, 0x54, 0xfd, 0x79, 0xd8, 0x15, 0x60, 0x53, 0xdc, 0x0e, 0x9f, 0x82,
	0x5b, 0x0d, 0x54, 0xbe, 0x13, 0xf6, 0x2b, 0x5b, 0x4d, 0xc0, 0x8e, 0xc1, 0xbd, 0xcd, 0x0a, 0xbd,
	0xb9, 0xfe, 0xeb, 0xc0, 0x99, 0xad, 0xfa, 0x46, 0x72, 0x9d, 0xc4, 0x84, 0xef, 0xc0, 0xb3, 0x3e,
	0xe3, 0xb4, 0x6b, 0xcb, 0xc1, 0xd3, 0xa8, 0x6b, 0x19, 0xac, 0x57, 0x15, 0x5a, 0x27, 0x77, 0x85,
	0xad, 0x1d, 0xec, 0x0a, 0xdb, 0x76, 0xb3, 0x1e, 0x46, 0xd0, 0xbf, 0x23, 0x8d, 0xe3, 0x68, 0xdf,
	0xe2, 0x00, 0xa3, 0x03, 0x37, 0x59, 0x0f, 0xdf, 0xc0, 0xa0, 0xfa, 0x8a, 0x58, 0x67, 0x1b, 0x26,
	0x04, 0x93, 0xe8, 0xd0, 0x03, 0xd6, 0xfb, 0x7c, 0xf2, 0xdd, 0xb3, 0xbf, 0xc2, 0x85, 0x67, 0xfe,
	0x64, 0xde, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xf8, 0x1f, 0x2e, 0x74, 0x04, 0x00, 0x00,
}
